name: Secrets & Variables GitHub Action pipeline

on:
  workflow_dispatch: 
  # push:
  #   branches: ["main"]

jobs:
  Basic:
    runs-on: [self-hosted, Linux]

    steps:
    - name: Print a variable
      run : echo ${{ vars.VARDEMO }}

    - name: Print a secret
      run: echo ${{ secrets.SECRDEMO }}
